system:
  port: 80
  connect-timeout: 10

cache:
  local-cache:
    cache-size: 500


mysql:
  username: paul
  password: password
  database: shorturl
  host: 127.0.0.1
  port: 3306
  query: parseTime=True&loc=Local&timeout=10000ms
  log-mode: true
  charset: utf8mb4
  collation: utf8mb4_general_ci
  maxConnect: 300
  iIdleConnect: 10

logs:
  path: ./logger/server.log
  level: INFO
