version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: shorturl
      MYSQL_USER: paul
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret
    ports:
     - 3306:3306