system:
  port: 80
  connect-timeout: 10

cache:
  cachesize: 500


mysql:
  username: root
  password: password
  database: shorturl
  host: 127.0.0.1
  port: 3306
  query: parseTime=True&loc=Local&timeout=10000ms
  log-mode: true
  charset: utf8mb4
  collation: utf8mb4_general_ci

logs:
  path: ./logger/server.log
  level: INFO
